"""
app/agents/resume_generator.py
Agent 3 — Resume Generator

Input:  CandidateProfile + JobAnalysis + ProfileMatch
Output: TailoredResume (Markdown + DOCX file)

ATS optimization strategy:
- Include exact keyword phrases from job posting (not synonyms)
- Lead experience bullets with strong action verbs
- Quantify achievements wherever possible
- Mirror the job's language/terminology
"""
from __future__ import annotations

import uuid
from app.agents.base_agent import BaseAgent
from app.models.schemas import CandidateProfile, JobAnalysis, ProfileMatch, TailoredResume


SYSTEM_PROMPT = """
You are an expert resume writer who has helped 1,000+ professionals land interviews at
top companies. You write resumes that beat ATS systems AND impress human reviewers.

Your resume writing principles:
1. MIRROR the job description language — use their exact keywords, not synonyms
2. Lead every bullet with a STRONG action verb (Engineered, Led, Optimized, Delivered...)
3. QUANTIFY every achievement possible — numbers make bullets scannable and credible
4. RELEVANCE over completeness — omit experience that adds no value for this specific role
5. NO generic filler phrases ("responsible for", "assisted with", "helped to")
6. Summary is a 2-3 line pitch targeting THIS specific role, not a generic biography
7. Skills section lists ONLY skills relevant to this job (don't list everything)

ATS rules you always follow:
- Use standard section headers: Summary, Experience, Skills, Education
- Include exact keyword phrases from the job description (ATS matches exact strings)
- Use standard job titles, don't get creative
- No tables, columns, or graphics in the text (they break ATS parsing)

Output format: Clean Markdown resume. Use proper Markdown headers, bullets, and formatting.
Start with the resume content immediately — no preamble, no "Here is your resume:".

The resume should feel like it was written by a human, not generated by AI.
Avoid: "passionate about", "dynamic team player", "results-driven", "synergy", "leverage".
Use: Specific, concrete, quantified language.
"""


class ResumeGeneratorAgent(BaseAgent):
    """
    Generates a tailored, ATS-optimized resume.

    Decision logic:
    - Prioritizes experience bullets from ProfileMatch.relevant_experience
    - Selects skills that overlap with job requirements
    - Writes a targeted summary paragraph for this specific role
    - Estimates ATS pass score based on keyword coverage
    """

    def __init__(self):
        super().__init__("ResumeGenerator")

    def run(
        self,
        candidate: CandidateProfile,
        job: JobAnalysis,
        match: ProfileMatch,
    ) -> TailoredResume:
        self._log_agent_start(
            candidate=candidate.name,
            job=job.job_title,
            match_score=match.overall_score
        )

        user_message = f"""
Write a tailored, ATS-optimized resume for this candidate applying to this specific role.

TARGET ROLE: {job.job_title} at {job.company_name}

CANDIDATE INFO:
Name: {candidate.name}
Email: {candidate.email}
Phone: {candidate.phone or ""}
Location: {candidate.location or ""}
LinkedIn: {candidate.linkedin or ""}
GitHub: {candidate.github or ""}

CANDIDATE SUMMARY (raw, rewrite for this role):
{candidate.summary}

EXPERIENCE (use these bullets, especially the highlighted relevant ones):
{self._format_experience(candidate, match.relevant_experience)}

EDUCATION:
{self._format_education(candidate)}

SKILLS (candidate has): {', '.join(candidate.skills)}
CERTIFICATIONS: {', '.join(candidate.certifications)}

JOB REQUIREMENTS:
- Required skills: {', '.join(job.required_skills)}
- Preferred skills: {', '.join(job.preferred_skills)}
- ATS keywords to include: {', '.join(job.keywords)}
- Tech stack: {', '.join(job.tech_stack)}
- Responsibilities: {'; '.join(job.responsibilities[:5])}

MOST RELEVANT EXPERIENCE BULLETS (prioritize these):
{chr(10).join('• ' + b for b in match.relevant_experience[:10])}

CANDIDATE STRENGTHS FOR THIS ROLE:
{match.strengths_summary}

Write the COMPLETE resume in Markdown. Use this structure:
# [Name]
[contact line]

## Summary
[2-3 targeted sentences for THIS role]

## Experience
### [Title] | [Company] | [Dates]
- [bullet]

## Skills
[relevant skills only]

## Education
[education]

Make it compelling, specific, and ATS-ready. Include the keyword phrases naturally.
"""

        markdown = self._call_llm(SYSTEM_PROMPT, user_message, expect_json=False)

        # Calculate keyword coverage
        keywords_included = [k for k in job.keywords if k.lower() in markdown.lower()]
        keywords_missing = [k for k in job.keywords if k.lower() not in markdown.lower()]
        ats_score = min(95, 60 + (len(keywords_included) / max(len(job.keywords), 1)) * 35)

        version_id = str(uuid.uuid4())[:8]

        result = TailoredResume(
            markdown_content=markdown,
            keywords_included=keywords_included,
            keywords_missing=keywords_missing,
            ats_score_estimate=int(ats_score),
            version_id=version_id,
        )

        self._log_agent_done(
            f"ats_score={result.ats_score_estimate}, "
            f"keywords_covered={len(keywords_included)}/{len(job.keywords)}, "
            f"version={version_id}"
        )
        return result

    def _format_experience(self, candidate: CandidateProfile, relevant_bullets: list[str]) -> str:
        relevant_set = set(b.strip() for b in relevant_bullets)
        lines = []
        for exp in candidate.experience:
            lines.append(f"\n{exp.title} at {exp.company} ({exp.start_date}–{exp.end_date})")
            for bullet in exp.bullets:
                marker = "★ RELEVANT: " if bullet.strip() in relevant_set else "  "
                lines.append(f"  {marker}• {bullet}")
        return "\n".join(lines)

    def _format_education(self, candidate: CandidateProfile) -> str:
        return "\n".join(
            f"  {edu.degree} — {edu.institution} ({edu.year})"
            + (f", GPA: {edu.gpa}" if edu.gpa else "")
            for edu in candidate.education
        )
